services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: parsect-server
    image: parsect-server:latest
    environment:
      - STALKERS_URL=${STALKERS_URL}
      - ROBOT_HEADER=${ROBOT_HEADER}
      - ROBOT_SECRET=${ROBOT_SECRET}
    ports:
      - "2025:80"
    networks:
      - parsect-network
    restart: unless-stopped

  client:
    container_name: parsect-client
    image: parsect-client:latest
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_PARSECT_URL=${VITE_PARSECT_URL}
    environment:
      - VITE_PARSECT_URL=${VITE_PARSECT_URL}
    ports:
      - 4173:4173
    networks:
      - parsect-network
    restart: unless-stopped

networks:
  parsect-network:
    name: parsect-network